In [1]:
import numpy as np
def cos_sim(vec1,vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

In [ ]:
import json
import csv
import numpy as np
import pandas as pd

In [1]:
import json
import csv
import numpy as np
import pandas as pd
def course_list():
    file=open("course_list.csv")
    file=csv.reader(file)
    file=list(file)
    course=[]
    for c in file:
        course.append(c)
    return course
corses=course_list()

37


In [1]:
import json
import csv
import numpy as np
import pandas as pd
def vocab_list():
    file=open("keyword_list.csv")
    file=csv.reader(file)
    keywor=[]
    for c in file:
        keywor.append(c)
    return keywor
vocab=vocab_list()
print(vocab)

[['演習'], ['特殊'], ['講義'], ['科学'], ['研究'], ['工学'], ['社会'], ['コース'], ['日本'], ['文化'], ['文学'], ['理学'], ['化学'], ['語学'], ['実習'], ['生物'], ['共通'], ['基礎'], ['情報'], ['特別'], ['英語'], ['環境'], ['シス'], ['システム'], ['国語'], ['国際'], ['専門'], ['数理'], ['経済'], ['概論'], ['実験'], ['言語'], ['力学'], ['教育'], ['日本語'], ['物理'], ['史学'], ['応用'], ['中国'], ['フランス'], ['現代'], ['心理'], ['生命数学'], ['開講'], ['分析'], ['心理学'], ['教養'], ['思想'], ['統計'], ['ドイツ'], ['政治'], ['論文'], ['中国語'], ['解析'], ['アメリカ'], ['哲学'], ['アジア'], ['建築'], ['物質'], ['イタリア'], ['第一'], ['科目'], ['技術'], ['倫理'], ['グローバル'], ['朝鮮'], ['設計'], ['韓国'], ['物理学'], ['地域'], ['国文学'], ['テクスト'], ['社会学'], ['地球'], ['生物学'], ['中級'], ['材料'], ['動物'], ['西洋'], ['外国語'], ['総合'], ['フランス語'], ['理論'], ['初級'], ['経済学分子'], ['自然'], ['ドイツ語'], ['国語学'], ['構造'], ['宇宙'], ['指導'], ['社会科'], ['人類'], ['都市'], ['ロシア'], ['解析学'], ['生命科学'], ['基礎科学'], ['社会科学'], ['比較'], ['卒業'], ['森林'], ['歴史'], ['経営'], ['プロジェクト'], ['航空'], ['情報学'], ['情報工学'], ['イタリア語'], ['資源'], ['量子'], ['ラテンアメリカ'], ['概説'], ['計画'], ['エネルギー'], ['人類学'], ['自然科学']

In [10]:
import json
import csv
import numpy as np
import pandas as pd
def count_df(courses,vocab):
    df={}
    for word_id, word in enumerate(vocab):
        count=0
        for c in courses:
            if word in c:
                count+=1
        df[word_id]=count
    return df
courses = list(open("course_list.csv"))
vocab = list(open("keyword_list.csv"))
df=count_df(courses,vocab)
print(df)

{0: 157, 1: 0, 2: 13, 3: 45, 4: 22, 5: 88, 6: 8, 7: 0, 8: 0, 9: 3, 10: 6, 11: 49, 12: 51, 13: 1, 14: 98, 15: 0, 16: 0, 17: 28, 18: 1, 19: 0, 20: 1, 21: 5, 22: 0, 23: 10, 24: 0, 25: 0, 26: 0, 27: 7, 28: 5, 29: 68, 30: 35, 31: 1, 32: 27, 33: 2, 34: 0, 35: 4, 36: 1, 37: 3, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 0, 44: 15, 45: 6, 46: 1, 47: 2, 48: 7, 49: 0, 50: 8, 51: 5, 52: 0, 53: 11, 54: 0, 55: 2, 56: 0, 57: 0, 58: 0, 59: 0, 60: 55, 61: 0, 62: 5, 63: 17, 64: 0, 65: 0, 66: 7, 67: 0, 68: 15, 69: 0, 70: 0, 71: 0, 72: 5, 73: 0, 74: 24, 75: 1, 76: 1, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 11, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 4, 89: 0, 90: 8, 91: 0, 92: 1, 93: 0, 94: 0, 95: 2, 96: 3, 97: 0, 98: 1, 99: 0, 100: 0, 101: 0, 102: 1, 103: 6, 104: 3, 105: 0, 106: 7, 107: 2, 108: 0, 109: 0, 110: 0, 111: 0, 112: 6, 113: 5, 114: 0, 115: 5, 116: 0, 117: 0, 118: 0, 119: 11, 120: 5, 121: 0, 122: 0, 123: 2, 124: 0, 125: 0, 126: 0, 127: 0, 128: 1, 129: 0, 130: 1, 131: 0, 132: 0, 133: 0, 134: 1, 135: 0,

In [12]:
import numpy as np
def lec_word_matrix(courses, vocab):
    lec_word=np.zeros((len(courses),len(vocab)),dtype=int)
    for i in range(len(courses)):
        for j in range(len(vocab)):
            if vocab[j] in courses[i]:
                lec_word[i][j]=1
    print(lec_word)
courses = list(open("course_list.csv"))
vocab = list(open("keyword_list.csv"))
lec_word_matrix(courses, vocab)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [1 0 0 ... 0 1 0]]


In [44]:
import numpy as np
def count_df(courses,vocab):
    df=np.zeros(len(vocab))
    for i, word in enumerate(vocab):
        for c in courses:
            if word in c:
                df[i]+=1
    return df
def lec_word_tfidf_matrix(courses, vocab,df):
    tfidf_matrix=np.zeros((len(courses),len(vocab)),dtype=int)
    for i, course in enumerate(courses):
        for j, word in enumerate(word_list):
            # Compute term frequency (TF)
            tf = course.count(word) / len(course)
            # Compute inverse document frequency (IDF)
            idf = np.log(len(courses) / df[j])
            # Compute TF-IDF
            tfidf_matrix[i, j] = tf * idf

    return tfidf_matrix

    
courses = list(open("course_list.csv"))
vocab = list(open("keyword_list.csv"))
df=count_df(courses,vocab)
print(lec_word_tfidf_matrix(courses, vocab,df))

C:\Users\reoha\AppData\Local\Temp\ipykernel_7208\230328439.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  idf = np.log(len(courses) / df[j])
C:\Users\reoha\AppData\Local\Temp\ipykernel_7208\230328439.py:18: RuntimeWarning: invalid value encountered in scalar multiply
  tfidf_matrix[i, j] = tf * idf


ValueError: cannot convert float NaN to integer

In [38]:
import numpy as np
def count_df(courses,vocab):
    df=np.zeros(len(vocab))
    for i, word in enumerate(vocab):
        for c in courses:
            if word in c:
                df[i]+=1
    return df
    
def lec_word_tfidf_matrix(courses, vocab,df):
    lec_word=np.zeros((len(courses),len(vocab)),dtype=int)
    for i in range(len(courses)):
        for j in range(len(vocab)):
            tf = courses.count(vocab[j]) / len(courses)
            idf = np.log(len(courses) / df[j])
            lec_word[i][j]=tf*idf
    return lec_word
                                                             
def cos_sim(vec1,vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1)) * np.linalg.norm(vec2)
            
def find_similar_course(target,matrix,courses):
    similar_courses = {}
    for i, course in enumerate(courses):
        if i != target_index:
            similarity = 1 - cos_sim(courses.index([title],matrix[i]))
            if similarity > 0:
                similar_courses[course] = similarity
    
    print(similar_courses)
courses = list(open("course_list.csv"))
vocab = list(open("keyword_list.csv"))
df=count_df(courses,vocab)
matrix=lec_word_tfidf_matrix(courses, vocab,df)
title="医学データの統計解析実習"
find_similar_course(courses.index([title]),matrix,courses)

C:\Users\reoha\AppData\Local\Temp\ipykernel_7208\1589659931.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  idf = np.log(len(courses) / df[j])
C:\Users\reoha\AppData\Local\Temp\ipykernel_7208\1589659931.py:16: RuntimeWarning: invalid value encountered in scalar multiply
  lec_word[i][j]=tf*idf


ValueError: cannot convert float NaN to integer

In [23]:
import numpy as np

def lec_word_tfidf_matrix(courses, word_list):
    """
    Create a TF-IDF matrix for lecture-word pairs.

    Args:
        courses (list of lists): List of lectures, where each lecture is a list of words.
        word_list (list): List of unique words.

    Returns:
        np.ndarray: TF-IDF matrix.
    """
    # Initialize an empty matrix
    tfidf_matrix = np.zeros((len(courses), len(word_list)))

    # Compute the document frequency (DF) for each word
    df = np.zeros(len(word_list))
    for i, word in enumerate(word_list):
        for course in courses:
            if word in course:
                df[i] += 1

    # Compute the TF-IDF values
    for i, course in enumerate(courses):
        for j, word in enumerate(word_list):
            # Compute term frequency (TF)
            tf = course.count(word) / len(course)
            # Compute inverse document frequency (IDF)
            idf = np.log(len(courses) / df[j])
            # Compute TF-IDF
            tfidf_matrix[i, j] = tf * idf

    return tfidf_matrix

# Example usage
courses = [
    ["machine", "learning", "deep", "learning"],
    ["natural", "language", "processing"],
    ["computer", "vision", "deep", "learning"],
]

word_list = ["machine", "learning", "deep", "natural", "language", "processing", "computer", "vision"]

# Call the function to create the TF-IDF matrix
tfidf_matrix = lec_word_tfidf_matrix(courses, word_list)

# Print the TF-IDF matrix
print(tfidf_matrix)

[[0.27465307 0.20273255 0.10136628 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.3662041  0.3662041  0.3662041
  0.         0.        ]
 [0.         0.10136628 0.10136628 0.         0.         0.
  0.27465307 0.27465307]]
